[package]
name = "emerald-legacy-launcher"
version = "1.6.1"
description = "A FOSS, cross-platform launcher for Minecraft Legacy Edition"
authors = ["Emerald Team"]
edition = "2024"

[lib]
name = "emerald_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = ["protocol-asset", "tray-icon", "image-png"] }
tauri-plugin-opener = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tauri-plugin-gamepad = "0.0.5"
reqwest = { version = "0.11", default-features = false, features = ["stream", "json", "rustls-tls-webpki-roots", "socks"] }
tokio = { version = "1", features = ["full"] }
futures-util = "0.3"
tokio-util = { version = "0.7.18", features = ["rt"] }
base64 = "0.21"
tokio-tungstenite = { version = "0.21", default-features = false, features = ["connect", "rustls-tls-webpki-roots"] }
url = "2"
rand = "0.8"
http = "1"
libc = "0.2"
image = "0.24"
steam_shortcuts_util = "1.1.8"
tauri-plugin-process = "2"
byteorder = "1"
flate2 = "1"
once_cell = "1"
lzxd = "0.2.6"
uuid = { version = "1", features = ["v4"] }
tauri-plugin-deep-link = "2"

[target.'cfg(target_os = "android")'.dependencies]
wry = { version = "0.54", default-features = false }
jni = "0.21"

[target.'cfg(not(any(target_os = "android", target_os = "ios")))'.dependencies]
tauri-plugin-updater = "2"
tauri-plugin-drpc = "*"
tauri-plugin-single-instance = "2"
rfd = "0.15"

#neo: enable portable appimages. revert back to crates.io once the PR is merged
#[patch.crates-io]
#tauri = { git = "https://github.com/tauri-apps/tauri", branch = "feat/truly-portable-appimage" }
#end neo
